### ISSUE TITLE
Blocked

### ISSUE THREAD

**Issue by ILOVETOMAKESTUFF** [JoshAtticus/joshatticus.github.io#2]
Lol, this is blocked, probably because it enables you to track me.

**Comment by JoshAtticus** [comment]
Blocked by what?

**Comment by ILOVETOMAKESTUFF** [comment]
My district. I use a chromebook. This is not a bug, just some info.

**Comment by JoshAtticus** [comment]
> My district. I use a chromebook. This is not a bug, just some info.

Ok, that has absolutely nothing to do with my website, that's your school. It works fine at my school, but I have added nothing to it.
