### ISSUE TITLE
Domain

### ISSUE THREAD

**Issue by lankybox02** [JoshAtticus/joshatticus.github.io#5]
I've acquired the domain joshatticus.eu.org
Would you like to use it?

**Comment by JoshAtticus** [comment]
Sure, if you're happy to transfer it. I don't currently have the money to pay for it though.

**Comment by JoshAtticus** [comment]
Or if you're happy to setup the domain for me

**Comment by JoshAtticus** [comment]
> I've acquired the domain joshatticus.eu.org Would you like to use it?

Don't know if you're still there, but if you are, could you respond?

**Comment by lankybox02** [comment]
hello

**Comment by lankybox02** [comment]
The domain is absolutely free. Would you like me to set it up?

**Comment by JoshAtticus** [comment]
> The domain is absolutely free. Would you like me to set it up?

Sure!
